title: Computing in Optimization and Statistics 2017
description: Course materials for the ORC's 2017 IAP course, "Computing in Optimization and Statistics"
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
